services:
  postgres:
    container_name: postgres-sql-cm
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: car_marketplace
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-cm
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1020:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
